version: "3"

services:
  db:
    container_name: db
    image: mysql:5.7.30
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

  api:
    container_name: api
    build: ./api/
    image: api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - ./api:/app:cached
      - bundle_data:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      app_net:
        ipv4_address: '172.20.0.3'
    
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   image: frontend
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   ports:
  #     - "3001:3000"
  #   command: sh -c "yarn start"
  #   networks:
  #     app_net:
  #       ipv4_address: '172.20.0.4'
    
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
  mysql_data:
  bundle_data: