default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: james_development

test:
  <<: *default
  database: james_test

production:
  <<: *default
  database: james_production
  username: james
  password: <%= ENV['JAMES_DATABASE_PASSWORD'] %>
  host: <%= ENV['JAMES_DATABASE_HOST'] %>
