name: Test

on:
  pull_request:
    branches: main

jobs:
  setup_and_test_execution:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            ruby-version: ['2.6.5']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: ./api

    - name: Setup Database
      run: |
        cp config/database.yml.ci config/database.yml
        sudo /etc/init.d/mysql start
        bundle exec rake db:create
        bundle exec rake db:schema:load
      working-directory: ./api
      env:
        RAILS_ENV: test

    - name: Run RSpec
      run: bundle exec rspec
      env:
        RAILS_ENV: test
      working-directory: ./api