name: Test

on:
  push:
    branches: main

jobs:
  setup_and_test_execution:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      with:
        ruby-version: 2.6.5

    - name: Install dependencies
      run:  bundle install
      working-directory: ./api

    - name: Setup Database
      run: |
        cp config/database.yml.ci config/database.yml
        sudo /etc/init.d/mysql start
        bundle exec rake db:create
        bundle exec rake db:schema:load
      working-directory: ./api
      env:
        RAILS_ENV: test

    - name: Run RSpec
      run: bundle exec rspec
      env:
        RAILS_ENV: test